### ISSUE TITLE
Theme refactor and maturation

### ISSUE THREAD

**Issue by benreyn** [dracula/emacs#20] opened 2017-03-01 17:17 UTC
Overall I love this theme, but I believe some of the issues we have run into ( #2 , and some of the  resulting errors discussed in the resolving #19 ) May be due to the architecture of this theme compared to many other more mature emacs theme (such as [solarized-emacs](https://github.com/bbatsov/solarized-emacs))

Im creating this issue to start the discussion around a refactor of the way this particular version of the dracula theme is architected and build up a more "bullet-proof" theme that will look nice in both an emacs gui, a standalone terminal session, and as a client session in a terminal connected to a running emacs server, as well as looking nice and consistent across many of the commonly used emacs packages. (dired+, mu4e, gnus, etc etc).

I am going to start this endeavor by digging deeper into the source of [solarized-emacs](https://github.com/bbatsov/solarized-emacs) and looking for other more mature emacs themes to look at for an example.

**Comment by benreyn** [comment] 2017-03-01 20:24
The [spacemacs theme](https://github.com/nashamri/spacemacs-theme) looks like another good one to look at.

**Comment by zenorocha** [comment] 2017-03-05 20:52
That's awesome! Thanks a lot @benjamreynolds for this research.

**Comment by eigengrau** [comment] 2017-03-08 08:24
In general the custom.el system provides a built-in system to switch faces based on output device type. This is already being used in the `class` macro. In #24 I replaced the current `display-graphic-p` switch with the custom.el way to do this, which does the right thing both when running one-off Emacs and when running it in daemon mode.

I only did this for the `default` face though. @benjamreynolds If there’s additional faces that look odd in the terminal this might a way to robustly customize them across display types.

**Comment by benreyn** [comment] 2017-03-08 14:02
good find @eigengrau, I dont often use emacs at my terminal so I would have to look into it. I recently did a switch to spacemacs and am going to spend some time (when I get it) trying to make sure dracula looks great on there.

**Comment by TheBaronHimself** [comment] 2017-06-27 10:20
I'm loving dracula, but don't like what it does to the mode-line in Spacemacs. Have a look:

![screen shot 2017-06-27 at 12 18 11](https://user-images.githubusercontent.com/11179011/27582905-eb55714a-5b32-11e7-9760-ce87a10e8d7c.png)

![screen shot 2017-06-27 at 12 23 50](https://user-images.githubusercontent.com/11179011/27583090-8cf60f78-5b33-11e7-94ab-2c40648e2804.png)


Maybe this could get some love in the refactor, too. I think Spacemacs' default dark theme is a good place to start.

**Comment by film42** [comment] 2017-06-28 17:52
@TheBaronHimself I think that's something that can be fixed pretty quickly. Would you mind opening a PR with the style changes needed and a before/ after screenshot?

**Comment by TheBaronHimself** [comment] 2017-06-28 21:09
@film42 | Sure thing. I put it on my to-do list.

**Comment by ghost** [comment] 2018-03-26 08:37
what's the status on this? it would be nice to get the terminal background fix from #32 in

**Comment by eigengrau** [comment] 2018-03-26 09:16
@untoreh It doesn’t look like anybody is working on redefining the colour theme based on a 256-colour palette right now. Basically, what someone needs to do is this:

1. For every color that is customized in some face, select the nearest appropriate color from the [256-color xterm palette](https://upload.wikimedia.org/wikipedia/commons/1/15/Xterm_256color_chart.svg).
2. Add those colors to the face definitions by adding a [display spec](https://www.gnu.org/software/emacs/manual/html_node/elisp/Defining-Faces.html) that is appropriate for the terminal (probably `tty`, not sure about Mac).

Certain terminals also support 24-bit color, in which case the colors would not have to be changed. However, Emacs currently does not support 24-bit color in terminals.

**Comment by eigengrau** [comment] 2018-03-26 09:21
Incidentally, Google also turned up [this package](https://github.com/tungd/color-theme-approximate) which does programmatic translation between 24-bit and 8-bit colors.

**Comment by ghost** [comment] 2018-03-28 10:06
@eigengrau the problem is that the background is set to black, if you look at dracula/xresources, black is actual black (color0), so in this case I don't think the problem is color translation but simply the fact that dracula emacs conflicts with the Xresources theme, in fact reloading the Xresources swapping out the black color and opening a new terminal the color applied is the new black color.

**Comment by eigengrau** [comment] 2018-03-28 10:15
@untoreh AFAICT the black was put in there on purpose (cf. #22) because of the color translation issue, so the best way to resolve it is to define a set of TTY-colors to be used. #22 was probably only done because the background color was the most obvious one, but in fact most of the colors are probably off from what they officially should be in the terminal.

**Comment by eigengrau** [comment] 2018-03-28 10:38
Just as an aside, what’s special about the background appears to be that `#000000` doesn’t show as black, but as terminal color 1 (which often defaults to black, but might be customized in Xresources or however your terminal is configured, as you mentioned). I’m not sure whether Emacs is purposely using the 16-color palette here, or whether the terminal’s 16-color palette affects the display of 256 xterm-colors.

**Comment by eigengrau** [comment] 2018-03-28 11:00
It looks like when entering colors in hex, Emacs (on tty) assumes that the 16-color palette is exactly the original xterm-palette and will use those (possibly redefined) colors when they are used as hex. In `M-x list-colors-display` you can see that the first 16 colors are the 16-color terminal palette, but listed with hexcodes that do not necessarily correspond to the color shown (i.e., if you customized your terminal palette to use beige as color 0, the table shows beige with hexcode `#000000`).

In order to use colors that are (hopefully) invariant between terminals one would need to select black as `"color-16"`, not as `#000000`. So whoever cares about the terminal enough to remap the Dracula colors to the 256 color palette would best use this notation instead of hex.

**Comment by eigengrau** [comment] 2018-03-28 11:36
Matching the Dracula background color will be really hard, btw. I guess that must be why Emacs degrades it to what appears to be xterm color 17 (dark blue). Looking at the palette, I don’t really see how one could do any better. Anything that’s pastel seems to be much more violet, or a lot brighter.

**Comment by ghost** [comment] 2018-05-01 03:33
@eigengrau I don't think you need to "match" dracula colors in terminal? Just provide correct mappings for .Xresources colors which should already be themed to dracula, or do nothing in case both emacs and the current terminal emulator support 24bit colors, iirc solarized worked with low bits TERM var + Xresources.

**Comment by eigengrau** [comment] 2018-05-01 06:58
@untoreh: currently, it is not really expected of users that they use a specific 16-color scheme in their terminal emulator. When they do, for now it is only the background color that will affect how a dracula-themed Emacs is displayed.

Even when people were asked to set up their terminal emulators in a specific way, there would have to be some remapping on the part of dracula, since the Emacs theme uses more than 16 colors.

> or do nothing in case both emacs and the current terminal emulator support 24bit colors

Emacs on the terminal currently does not support 24-bit colors, for now.

**Comment by eigengrau** [comment] 2018-05-31 08:24
`C-h n` informs me that the newly released Emacs 26.1 now supports 24-bit colors if the terminal emulator supports it.

**Comment by milouse** [comment] 2020-02-10 19:30
> @untoreh It doesn’t look like anybody is working on redefining the colour theme based on a 256-colour palette right now. […]

I think we should definitely look at the [doom-dracula theme](https://github.com/hlissner/emacs-doom-themes/blob/master/themes/doom-dracula-theme.el) for a 256 colors palette.

**Comment by milouse** [comment] 2020-02-11 08:57
I close this ticket in favor of #32

**Closed as completed by milouse** 2020-02-11 08:57 UTC
